stages:
  - build


build.develop:
  stage: build
  before_script:
    - CI_FULL_REGISTRY=bridge-landing:develop
  variables:
    CI_FULL_REGISTRY: ""
    NODE_ENV: production
    NODE_APP_INSTANCE: develop
    PORT: 36491
  script:
    - docker build --cache-from $CI_FULL_REGISTRY -t $CI_FULL_REGISTRY .
    - docker-compose -p bridge-develop up -d
  only:
    - develop
    - ECHO-1113
  tags:
    - bridge-dev
  environment:
    name: develop
    url: https://649-bridge-landing.pixelplex-test.by


build.master:
  stage: build
  before_script:
    - CI_FULL_REGISTRY=bridge-landing:master
  variables:
    CI_FULL_REGISTRY: ""
    NODE_ENV: production
    NODE_APP_INSTANCE: master
    PORT: 36491
  script:
    - docker build --cache-from $CI_FULL_REGISTRY -t $CI_FULL_REGISTRY .
    - docker-compose -p bridge-develop up -d
  only:
    - master
    - ECHO-1113
  tags:
    - bridge-dev
  environment:
    name: stage
    url: http://649-bridge-landing.pixelplexlabs.com
