stages:
  - test
  - build

eslint:
  image: node:10.15
  stage: test
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - node_modules/
  script:
    - npm i --silent
    - npm run lint
  tags:
    - docker
  only:
      - merge_requests
      - develop
      - master

build.develop:
  stage: build
  variables:
    NODE_ENV: production
    NODE_APP_INSTANCE: develop
  script:
    - docker build --build-arg NODE_APP_INSTANCE=${NODE_APP_INSTANCE} -t 649.bridge.landing . --no-cache
    - docker-compose down
    - docker-compose up -d
  only:
    - develop
  tags:
    - pp-develop
  environment:
    name: develop
    url: https://649-bridge-landing.pixelplex-test.by

build.master:
  stage: build
  variables:
    NODE_ENV: production
    NODE_APP_INSTANCE: master
  script:
    - docker build --build-arg NODE_APP_INSTANCE=${NODE_APP_INSTANCE} -t 649.bridge.landing . --no-cache
    - docker-compose down
    - docker-compose up -d
  only:
    - master
  tags:
    - pp-stage
  environment:
    name: master
    url: http://649-bridge-landing.pixelplexlabs.com