stages:
  - test
  - build

eslint:
  image: node:10.15
  stage: test
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - node_modules/
  script:
    - npm i --silent
    - npm run lint
  tags:
    - docker

build.develop:
  stage: build
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - npm i
    - npm run build-dev
    - rm -rf /home/frontend
    - cp -r ./dist /home/frontend
  only:
    - develop
  tags:
    - develop
  environment:
    name: development

build.master:
  stage: build
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - npm i
    - npm run build-stage
    - rm -rf /home/frontend
    - cp -r ./dist /home/frontend
  only:
    - master
  tags:
    - stage
  environment:
    name: stage
