apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: echoprotocol/bridge-website:latest
          imagePullPolicy: Always
          name: website
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: website
