apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-website
spec:
  spec:
  selector:
    matchLabels:
      app: website
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image:
          imagePullPolicy: Always
          name: bridge-website
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: website-lb
spec:
  type: LoadBalancer
  ports:
  - port: 36491
    protocol: TCP
    targetPort: 80
  selector:
    app: website
