name: Deploy
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show k8s-kluster-test > $GITHUB_WORKSPACE/.kubeconfig
    - name: deploy
      run: |
        export KUBECONFIG=.kubeconfig
        kubectl apply -f ./kubernetes/deployment.yml
