name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: echoprotocol/bridge-website:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up kubectl
      uses: matootie/dokube@v1.2.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        clusterName: k8s-kluster
        expirationTime: 300

    - name: Create deployment
      run: kubectl create -f ./kubernetes/deployment.yml --record
